### ISSUE TITLE
Editing chapters

### ISSUE THREAD

**Issue by PaulWoitaschek** [jangler/taffy#3]
As far as I know taglib supports chapter marks:

https://github.com/taglib/taglib/pull/173/files

Is this supported by this application?

**Comment by jangler** [comment]
Although TagLib itself supports the CHAP and CTOC frames, taglib-ruby doesn't. See https://github.com/robinst/taglib-ruby/issues/63 .

I'm going to close this as wontfix for now, but if taglib-ruby does gain this capability then I'd be willing to implement it in Taffy.
