### ISSUE TITLE
Lost my Spaces?

### ISSUE THREAD

**Issue by KharmaScribbles** [jangler/taffy#7]
Hello, this is a great tool and exactly what I have been looking for.

Before diving in to my actual collection, I segregated a few tracks to test exactly how this works, but I am confused by a few things.   

According to the readme, renaming a file based on it's tags is as simple as:
`taffy -n 14 -t "Queen of the Mole People" --rename "%n - %T song.mp3"`
Should output:
> "14 - Queen of the Mole People.mp3" 
 
However, this was _my_ exact command:
`taffy -r "The Tragically Hip" -l "Fully Completely" -y "1992" -t "Wheat Kings" --rename "%R - %T" "Wheat Kings.mp3"` 
          
What did I expect?

> The Tragically Hip - Wheat Kings.mp3

What did I get?

> TheTragicallyHip - WheatKings.mp3

In the ReadME, it shows basically the same command preserving spaces. Has something changed? What did I do wrong?

**Comment by jangler** [comment]
Huh, I guess something did change at some point. Incidentally, I'm about to merge a related change that will add a `--rename-fs` option that preserves spaces, apostrophes, and whatever other characters a filesystem can handle. The `--rename` option will stay roughly same and will liberally strip special characters.

Thanks for pointing out that the readme became wrong at some point. Or possibly was never right in the first place.

**Comment by jangler** [comment]
Resolved in 1.4.0.
