### ISSUE TITLE
Cover art support?

### ISSUE THREAD

**Issue by davidegreenwald** [jangler/taffy#8]
Thanks for this great tool. Any chance you could add support for attaching cover art?

**Comment by jangler** [comment]
Unfortunately no, as I don't plan to add support for format-specific metadata, i.e. tags not covered by [TagLib's generic top-level Tag interface](https://taglib.org/api/classTagLib_1_1Tag.html).

**Comment by davidegreenwald** [comment]
Thanks for considering.
